### PR TITLE
PuzzleBang and MechMania pages updated, navbar with events tab.

### PR DESCRIPTION
**Pull request by vibhav2799**
Addresses #42.

### CODE REVIEW

**Comment by PradyumnaShome** [comment]
Why did you merge the FAQ feature branch?

**Comment by modnikhil** [comment]
Looks good! Just a couple style things:
1) Can you make it so that the events sub-items appear when you hover over the "events" tab, not just click on the tab?
2) When the events tab is clicked, it maintains this white background that messes with the text's visibility. Change that effect to make the tab look "pressed" instead of turning white.
3) Change the font of the sub-items to match the rest of the navbar
4) When in the MechMania page or the PuzzleBang page, keep that events tab in the navbar instead of replacing it with just MechMania or just PuzzleBang

**Comment by modnikhil** [comment]
screenshot from 2018-07-25 17-13-16
This is what I was referring to with 2)

**Comment by vibhav2799** [comment]
Hey Nikhil,
Fixed all the issues. (Need to change carousel images to MechMania ones. Will do that in a couple of days).

Let me know if anything still needs to be fixed!

**Comment by PradyumnaShome** [comment]
As it stands, the content has been added, but some styling is left. The current status has been verified through a live demo, so we can have more reviews after more has been done.

**Pull request closed without merging**
